[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"

[functions]
  directory = "netlify/functions"
  
[build.environment]

[[redirects]]
  from = "https://barberpressure.netlify.app/*"
  to = "https://barberpressure.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/formsubmissions"
  to = "/.netlify/functions/submissions"
  status = 200

[[redirects]]
  from = "/api/formsubmissions/*"
  to = "/.netlify/functions/submissions/:splat"
  status = 200