[build]
base = "frontend"  # Your frontend code is in the 'frontend' directory
publish = "dist"   # Your frontend build output is in 'frontend/dist'
command = "npm run build"

# --- Redirects (remain as they were) ---
[[redirects]]
  from = "https://barberpressure.netlify.app/*"
  to = "https://barberpressure.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/formsubmissions"
  to = "/.netlify/functions/handler" # Still points to the /handler endpoint
  status = 200

[[redirects]]
  from = "/api/formsubmissions/*"
  to = "/.netlify/functions/handler"
  status = 200

[functions]
directory = "netlify/functions" 
