service: barber-son-api

provider:
  name: aws
  runtime: nodejs22.x        # match what's in AWS Console
  region: us-east-2          # match your deployed region

functions:
  submitForm:
    name: submitForm         # ⚠ MUST match your Lambda name in Console
    handler: handler.submitForm
    events:
      - http:
          path: form         # ⚠ MUST match existing API Gateway route
          method: post
          cors: true         # If your frontend is on another domain
